# helpdesk_mini/config/urls.py
from django.views.generic import TemplateView
# from django.views.generic import TemplateView # <--- ADD THIS


from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter

# Import the views we created in Step 6
from tickets.views import TicketViewSet, HealthView, MetaView 

# ----------------- 1. SET UP ROUTERS -----------------

# Main Router for top-level resources (/api/tickets)
# This still uses DefaultRouter for the TICKET endpoints, which works fine.
router = DefaultRouter()
router.register(r'tickets', TicketViewSet, basename='ticket')


# ----------------- 2. URL PATTERNS -----------------

urlpatterns = [

    path('', TemplateView.as_view(template_name='index.html')),
    # Django Admin page
    path('admin/', admin.site.urls),
    
    # Core API Endpoints: /api/tickets/ and /api/tickets/:id/ (Generated by router)
    path('api/', include(router.urls)),        
    
    # MANUAL WIRING FOR COMMENTS (Replaces the failed nested router)
    # POST /api/tickets/1/comments/ (Action defined in TicketViewSet)
    path('api/tickets/<int:pk>/comments', 
         TicketViewSet.as_view({'post': 'comments'}), 
         name='ticket-comments'),
    
    # Optional: Login/Logout views for testing (using DRF browsable API)
    path('api/auth/', include('rest_framework.urls')), 
    
    # Mandatory Meta Endpoints (Judge Check)
    path('api/health', HealthView.as_view()),
    path('api/meta', MetaView.as_view()),
    
    # Note: /.well-known/hackathon.json is skipped for the MVP
]   